_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SSRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 8
  SS:
    FEAT_LEVEL: "res4"
    NAME: ["build_rotation_head"]
    LOSS_SCALE: 0.5
    RATIO: 2.0
DATASETS:
  CROSS_DOMAIN: True
  TRAIN_SOURCE: ("cityscapes_train",)
  TRAIN_TARGET: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SOLVER:
  # the size of the BDD tracking daytime is about 2x of the BDD100k dataset
  # for initial experiments, this schedule will be approximately, 0.5X schedule
  # ~5 epochs
  IMS_PER_BATCH: 32
  BASE_LR: 0.01
  STEPS: (6000, 8000)
  MAX_ITER: 10000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
OUTPUT_DIR: "checkpoints/uda/city2foggy/R101_FPN_rot"