
_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DASSRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    # OUT_FEATURES: ["res2", "res3", "res4"]
  ROI_HEADS:
    NUM_CLASSES: 8
    NAME: "TLRes5ROIHeads"
  PROPOSAL_GENERATOR:
    NAME: "TLRPN"
  DA:
    IMG_FEAT_LEVEL: "res4"
    IMG_LOSS_SCALE: 0.5
  SS:
    FEAT_LEVEL: "res4"
    NAME: ["build_rotation_head"]
    LOSS_SCALE: 0.5
    RATIO: 2.0
DATASETS:
  CROSS_DOMAIN: True
  TRAIN_SOURCE: ("cityscapes_train",)
  TRAIN_TARGET: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (12000, )
  MAX_ITER: 16000
  WARMUP_ITERS: 100
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
OUTPUT_DIR: "checkpoints/uda/city2foggy/R101_C4_da_rot"