_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DARCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 8
    NAME: "TLRes5ROIHeads"
  PROPOSAL_GENERATOR:
    NAME: "TLRPN"
DATASETS:
  CROSS_DOMAIN: True
  TRAIN_SOURCE: ("cityscapes_train",)
  TRAIN_TARGET: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (6000, 8000)
  MAX_ITER: 10000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
OUTPUT_DIR: "checkpoints/uda/city2foggy/R101_C4_da"