_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SSRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 3
  SS:
    FEAT_LEVEL: "res4"
    NAME: ["build_cycle_head"]
    LOSS_SCALE: 0.01
    COEF: 1.0
DATASETS:
  TRAIN: ("waymo_front_right_train",)
  TEST: ("bdd_tracking_2k_val_night_3cls",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  STEPS: (36000, 48000,)
  MAX_ITER: 52500
  WARMUP_ITERS: 1000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
DATALOADER:
  SAMPLER_TRAIN: "PairTrainingSampler"
  PAIR_OFFSET_RANGE: 5
OUTPUT_DIR: "checkpoints/waymo_reported/R50_FPN_front_right_cycle_conf"